version: '2'
services:
  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/init/migrate.sh:/migrate.sh
      - ./db/migrations:/migrations
    ports:
      - '13306:3306'
  web:
    build: ./web
    ports:
      - '8080:80'
    environment:
      - APP_ENV=development
      - TZ=Japan
    volumes:
      - ./web:/var/www/html
    links:
      - db
